import os
import sqlite3
import pandas as pd

from alert_config import get_recipients
from email_notifier import send_email

INPUT_FILE = "model_output/inference_predictions_explained.csv"
DB_FILE = "model_output/scoring.db"

RISK_JUMP_THRESHOLD = 0.20
HIGH_PRIORITY_THRESHOLD = 70
NO_PROGRESS_THRESHOLD = 1.0
NO_PROGRESS_QUARTERS = 3


def create_alerts(df):
    alerts = []

    for _, row in df.iterrows():

        # Get recommendations already generated by explain_and_score.py
        recommendations = row.get("recommended_actions", "")

        if pd.isna(recommendations):
            recommendations = ""

        # 1. Newly High Risk
        if bool(row.get("newly_high_risk", False)):
            alerts.append({
                "project_id": row["project_id"],
                "quarter": row["quarter"],
                "region_final": row.get("region_final", "Unknown"),
                "sector_extracted": row.get("sector_extracted", "UNKNOWN"),
                "alert_type": "Newly High Risk",
                "severity": "Critical",
                "message": "Project has moved into the High risk tier.",
                "recommended_actions": recommendations
            })

        # 2. Large risk probability jump
        previous = row.get("previous_probability")

        if pd.notna(previous):
            jump = row["predicted_delay_probability"] - previous

            if jump >= RISK_JUMP_THRESHOLD:
                alerts.append({
                    "project_id": row["project_id"],
                    "quarter": row["quarter"],
                    "region_final": row.get("region_final", "Unknown"),
                    "sector_extracted": row.get("sector_extracted", "UNKNOWN"),
                    "alert_type": "Risk Score Jump",
                    "severity": "High",
                    "message": (
                        f"Delay probability increased by "
                        f"{jump * 100:.1f} percentage points."
                    ),
                    "recommended_actions": recommendations
                })

        # 3. High priority
        if row["priority_score"] >= HIGH_PRIORITY_THRESHOLD:
            alerts.append({
                "project_id": row["project_id"],
                "quarter": row["quarter"],
                "region_final": row.get("region_final", "Unknown"),
                "sector_extracted": row.get("sector_extracted", "UNKNOWN"),
                "alert_type": "High Priority",
                "severity": "High",
                "message": (
                    f"Priority score is "
                    f"{row['priority_score']:.2f}."
                ),
                "recommended_actions": recommendations
            })

    return pd.DataFrame(alerts)


def dispatch_alert_emails(alerts):
    if alerts.empty:
        print("No alerts to email.")
        return alerts

    alerts = alerts.copy()

    alerts["notification_sent"] = False
    alerts["notification_recipients"] = ""

    conn = sqlite3.connect(DB_FILE)

    for index, alert in alerts.iterrows():

        # Check if this alert was already emailed
        existing = conn.execute("""
            SELECT notification_sent
            FROM alerts
            WHERE project_id = ?
              AND quarter = ?
              AND alert_type = ?
        """, (
            alert["project_id"],
            alert["quarter"],
            alert["alert_type"]
        )).fetchone()

        if existing and bool(existing[0]):
            print(
                f"Skipping already-notified alert: "
                f"{alert['project_id']} / "
                f"{alert['alert_type']}"
            )
            alerts.at[index, "notification_sent"] = True
            continue

        recipients = get_recipients(
            alert["region_final"],
            alert["sector_extracted"]
        )

        if not recipients:
            print(
                f"No recipient configured for "
                f"{alert['project_id']}"
            )
            continue

        subject = (
            f"[{alert['severity']}] "
            f"Infrastructure Project Alert - "
            f"{alert['project_id']}"
        )

        message = f"""
Infrastructure Project Risk Alert

Project ID: {alert['project_id']}
Quarter: {alert['quarter']}

Alert type: {alert['alert_type']}
Severity: {alert['severity']}

Region: {alert['region_final']}
Sector: {alert['sector_extracted']}

Message:
{alert['message']}

Please review the project in the Infrastructure Delay Risk Dashboard.
"""

        sent = send_email(
            recipients,
            subject,
            message.strip()
        )

        alerts.at[index, "notification_sent"] = sent
        alerts.at[index, "notification_recipients"] = ", ".join(recipients)

    conn.close()

    return alerts
def save_alerts(alerts):
    if alerts.empty:
        print("No alerts generated.")
        return

    conn = sqlite3.connect(DB_FILE)

    # Create alerts table if it doesn't exist
    conn.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_id TEXT,
            quarter TEXT,
            region_final TEXT,
            sector_extracted TEXT,
            alert_type TEXT,
            severity TEXT,
            message TEXT,
            recommended_actions TEXT,
            notification_sent BOOLEAN DEFAULT 0,
            notification_recipients TEXT
        )
    """)

    for _, alert in alerts.iterrows():

        # Check whether this exact alert already exists
        existing = conn.execute("""
            SELECT 1
            FROM alerts
            WHERE project_id = ?
              AND quarter = ?
              AND alert_type = ?
        """, (
            alert["project_id"],
            alert["quarter"],
            alert["alert_type"]
        )).fetchone()

        if existing:
            continue

        conn.execute("""
            INSERT INTO alerts (
                project_id,
                quarter,
                region_final,
                sector_extracted,
                alert_type,
                severity,
                message,
                recommended_actions,
                notification_sent,
                notification_recipients
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            alert["project_id"],
            alert["quarter"],
            alert["region_final"],
            alert["sector_extracted"],
            alert["alert_type"],
            alert["severity"],
            alert["message"],
            alert.get("recommended_actions", ""),
            bool(alert.get("notification_sent", False)),
            alert.get("notification_recipients", "")
        ))

    conn.commit()
    conn.close()

    print(f"Saved alerts to database -> {DB_FILE}")


def main():
    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(
            f"Could not find {INPUT_FILE}"
        )

    df = pd.read_csv(INPUT_FILE)

    print(f"Loaded {len(df)} scored projects.")

    alerts = create_alerts(df)


    print(f"Generated {len(alerts)} alerts.")

    alerts = dispatch_alert_emails(alerts)

    save_alerts(alerts)

    if not alerts.empty:
        print("\nAlert distribution:")
        print(alerts["alert_type"].value_counts())

        print("\nSample alerts:")
        print(alerts.head(10).to_string(index=False))


if __name__ == "__main__":
    main()